# Практична робота 9
## Перетворення даних: похідні змінні, дискретизація, масштабування та індикаторне кодування

**Варіант:** 7  
**Місто:** Івано-Франківськ  
**Базова ціна:** 760 грн  
**Базова кількість:** 3  

**Студент:** Nazar Pryimachuk  
**Група:** IT-42

## Завдання 1. Побудова набору клієнтів

Створимо DataFrame із 10 замовленнями інтернет-магазину. Для кожного клієнта вкажемо вік, місячний дохід, кількість товару та місто доставки.

In [21]:
import pandas as pd

base_price = 760

df = pd.DataFrame({
    "вік": [19, 23, 28, 34, 39, 45, 51, 57, 63, 69],
    "дохід": [18000, 24000, 32000, 41000, 47000, 55000, 62000, 70000, 82000, 95000],
    "кількість": [2, 3, 4, 3, 5, 2, 4, 3, 6, 2],
    "місто_доставки": [
        "Івано-Франківськ",
        "Львів",
        "Київ",
        "Одеса",
        "Івано-Франківськ",
        "Дніпро",
        "Львів",
        "Київ",
        "Одеса",
        "Івано-Франківськ"
    ]
})

df

   вік  дохід  кількість    місто_доставки
0   19  18000          2  Івано-Франківськ
1   23  24000          3             Львів
2   28  32000          4              Київ
3   34  41000          3             Одеса
4   39  47000          5  Івано-Франківськ
5   45  55000          2            Дніпро
6   51  62000          4             Львів
7   57  70000          3              Київ
8   63  82000          6             Одеса
9   69  95000          2  Івано-Франківськ

In [22]:
df["сума_замовлення"] = base_price * df["кількість"]

df["частка_доходу"] = df["сума_замовлення"] / df["дохід"]

df

   вік  дохід  кількість    місто_доставки  сума_замовлення  частка_доходу
0   19  18000          2  Івано-Франківськ             1520       0.084444
1   23  24000          3             Львів             2280       0.095000
2   28  32000          4              Київ             3040       0.095000
3   34  41000          3             Одеса             2280       0.055610
4   39  47000          5  Івано-Франківськ             3800       0.080851
5   45  55000          2            Дніпро             1520       0.027636
6   51  62000          4             Львів             3040       0.049032
7   57  70000          3              Київ             2280       0.032571
8   63  82000          6             Одеса             4560       0.055610
9   69  95000          2  Івано-Франківськ             1520       0.016000

## Завдання 3. Дискретизація

Розіб'ємо вік клієнтів на 3 групи двома способами: за допомогою `pd.cut()` та `pd.qcut()`.

In [23]:
df["вік_група_cut"] = pd.cut(df["вік"], bins=3)

cut_counts = df["вік_група_cut"].value_counts().sort_index()

print("Розподіл клієнтів за pd.cut():")
print(cut_counts)

Розподіл клієнтів за pd.cut():
вік_група_cut
(18.95, 35.667]     4
(35.667, 52.333]    3
(52.333, 69.0]      3
Name: count, dtype: int64

In [24]:
df["вік_група_qcut"] = pd.qcut(df["вік"], q=3)

qcut_counts = df["вік_група_qcut"].value_counts().sort_index()

print("Розподіл клієнтів за pd.qcut():")
print(qcut_counts)

Розподіл клієнтів за pd.qcut():
вік_група_qcut
(18.999, 34.0]    4
(34.0, 51.0]      3
(51.0, 69.0]      3
Name: count, dtype: int64

In [25]:
comparison = pd.DataFrame({
    "cut": cut_counts.reset_index(drop=True),
    "qcut": qcut_counts.reset_index(drop=True)
})

comparison

   cut  qcut
0    4     4
1    3     3
2    3     3

### Порівняння `cut()` і `qcut()`

`pd.cut()` ділить діапазон значень на інтервали однакової ширини, тому кількість клієнтів у групах може відрізнятися.

`pd.qcut()` ділить дані за квантилями та намагається отримати приблизно однакову кількість спостережень у кожній групі.

Тому при однакових вхідних даних результати `cut()` і `qcut()` можуть відрізнятися: `cut()` орієнтується на ширину інтервалів, а `qcut()` — на кількість спостережень.

## Завдання 4. Масштабування

Виконаємо min-max нормалізацію та стандартизацію методом z-оцінки для змінних `вік` і `дохід`.

In [26]:
# Min-Max нормалізація

df["вік_minmax"] = (
    (df["вік"] - df["вік"].min()) /
    (df["вік"].max() - df["вік"].min())
)

df["дохід_minmax"] = (
    (df["дохід"] - df["дохід"].min()) /
    (df["дохід"].max() - df["дохід"].min())
)

df[["вік", "дохід", "вік_minmax", "дохід_minmax"]].head()

   вік  дохід  вік_minmax  дохід_minmax
0   19  18000        0.00      0.000000
1   23  24000        0.08      0.077922
2   28  32000        0.18      0.181818
3   34  41000        0.30      0.298701
4   39  47000        0.40      0.376623

In [27]:
df["вік_z"] = (
    (df["вік"] - df["вік"].mean()) /
    df["вік"].std()
)

df["дохід_z"] = (
    (df["дохід"] - df["дохід"].mean()) /
    df["дохід"].std()
)

In [28]:
df[[
    "вік",
    "дохід",
    "вік_minmax",
    "дохід_minmax",
    "вік_z",
    "дохід_z"
]].head()

   вік  дохід  вік_minmax  дохід_minmax     вік_z   дохід_z
0   19  18000        0.00      0.000000 -1.390253 -1.379178
1   23  24000        0.08      0.077922 -1.156597 -1.140014
2   28  32000        0.18      0.181818 -0.864527 -0.821129
3   34  41000        0.30      0.298701 -0.514043 -0.462383
4   39  47000        0.40      0.376623 -0.221973 -0.223220

### Пояснення

До масштабування `вік` і `дохід` мають різний порядок величини та різні одиниці вимірювання. Вік має значення від 19 до 69 років, а дохід — від 18000 до 95000 гривень.

Через це в методах, чутливих до масштабу, дохід міг би мати значно більший вплив на результат лише через великі числові значення.

Min-max нормалізація переводить значення у діапазон від 0 до 1.

Z-стандартизація перетворює значення так, щоб вони характеризували відхилення від середнього у стандартних відхиленнях.

Тому після масштабування `вік` і `дохід` можна коректніше використовувати разом.

In [29]:
city_dummies = pd.get_dummies(
    df["місто_доставки"],
    prefix="місто",
    dtype=int
)

city_dummies

   місто_Івано-Франківськ  місто_Дніпро  місто_Київ  місто_Львів  місто_Одеса
0                       1             0           0            0            0
1                       0             0           0            1            0
2                       0             0           1            0            0
3                       0             0           0            0            1
4                       1             0           0            0            0
5                       0             1           0            0            0
6                       0             0           0            1            0
7                       0             0           1            0            0
8                       0             0           0            0            1
9                       1             0           0            0            0

In [30]:
unique_cities = df["місто_доставки"].nunique()
dummy_columns = city_dummies.shape[1]

print("Кількість унікальних міст:", unique_cities)
print("Кількість dummy-стовпців:", dummy_columns)

Кількість унікальних міст: 5
Кількість dummy-стовпців: 5

In [31]:
df_encoded = pd.concat([df, city_dummies], axis=1)

df_encoded

,вік,дохід,кількість,місто_доставки,сума_замовлення,частка_доходу,вік_група_cut,вік_група_qcut,вік_minmax,дохід_minmax,вік_z,дохід_z,місто_Івано-Франківськ,місто_Дніпро,місто_Київ,місто_Львів,місто_Одеса
0,19,18000,2,Івано-Франківськ,1520,0.084444,"(18.95, 35.667]","(18.999, 34.0]",0.00,0.000000,-1.390253,-1.379178,1,0,0,0,0
1,23,24000,3,Львів,2280,0.095000,"(18.95, 35.667]","(18.999, 34.0]",0.08,0.077922,-1.156597,-1.140014,0,0,0,1,0
2,28,32000,4,Київ,3040,0.095000,"(18.95, 35.667]","(18.999, 34.0]",0.18,0.181818,-0.864527,-0.821129,0,0,1,0,0
3,34,41000,3,Одеса,2280,0.055610,"(18.95, 35.667]","(18.999, 34.0]",0.30,0.298701,-0.514043,-0.462383,0,0,0,0,1
4,39,47000,5,Івано-Франківськ,3800,0.080851,"(35.667, 52.333]","(34.0, 51.0]",0.40,0.376623,-0.221973,-0.223220,1,0,0,0,0
5,45,55000,2,Дніпро,1520,0.027636,"(35.667, 52.333]","(34.0, 51.0]",0.52,0.480519,0.128511,0.095666,0,1,0,0,0
6,51,62000,4,Львів,3040,0.049032,"(35.667, 52.333]","(34.0, 51.0]",0.64,0.571429,0.478995,0.374690,0,0,0,1,0
7,57,70000,3,Київ,2280,0.032571,"(52.333, 69.0]","(51.0, 69.0]",0.76,0.675325,0.829478,0.693575,0,0,1,0,0
8,63,82000,6,Одеса,4560,0.055610,"(52.333, 69.0]","(51.0, 69.0]",0.88,0.831169,1.179962,1.171903,0,0,0,0,1
9,69,95000,2,Івано-Франківськ,1520,0.016000,"(52.333, 69.0]","(51.0, 69.0]",1.00,1.000000,1.530446,1.690091,1,0,0,0,0

In [32]:
assert unique_cities == dummy_columns

print("Перевірка успішна!")
print("Кількість dummy-стовпців дорівнює кількості унікальних міст.")

Перевірка успішна!
Кількість dummy-стовпців дорівнює кількості унікальних міст.

### Пояснення one-hot кодування

`місто_доставки` є номінальною змінною, оскільки міста не мають природного порядку.

Якщо присвоїти містам числа 1, 2, 3, 4, алгоритм може помилково сприйняти ці числа як порядок або відстань між містами.

One-hot кодування створює окремий бінарний стовпець для кожного міста. Значення 1 означає, що замовлення доставляється до цього міста, а 0 — що ні.

Тому для змінної `місто_доставки` one-hot кодування є правильнішим за порядкове або просте числове кодування.

## Відповіді на контрольні питання

### 1. Яка різниця між `pd.cut()` і `pd.qcut()`?

`pd.cut()` розбиває діапазон числових значень на інтервали однакової ширини. Кількість спостережень у групах при цьому може бути різною.

`pd.qcut()` використовує квантилі та намагається сформувати групи з приблизно однаковою кількістю спостережень. При цьому ширина інтервалів може відрізнятися.

### 2. Чому для міста використовують one-hot кодування?

Місто є номінальною змінною і не має природного порядку. Присвоєння містам чисел 1, 2, 3 тощо створило б штучний порядок.

One-hot кодування створює окрему ознаку для кожного міста без створення такого порядку.

### 3. Навіщо масштабувати змінні?

Масштабування потрібне, щоб змінні з різними одиницями вимірювання та різним порядком величини мали порівнянний вплив на алгоритм.

Це особливо важливо для дистанційних методів та регресії з регуляризацією.

### 4. Навіщо створювати похідні змінні?

Похідна змінна може показувати співвідношення між декількома характеристиками.

Наприклад, `частка_доходу` показує, яку частину місячного доходу клієнт витратив на замовлення. Це дозволяє краще порівнювати клієнтів із різним рівнем доходу.

## Висновок

У практичній роботі було створено набір даних із 10 клієнтів для варіанта 7.

Було розраховано похідні змінні `сума_замовлення` та `частка_доходу`. Вік клієнтів було дискретизовано методами `pd.cut()` та `pd.qcut()` і порівняно отримані групи.

Для змінних `вік` і `дохід` виконано min-max нормалізацію та z-стандартизацію.

Змінну `місто_доставки` було закодовано методом one-hot encoding.

Таким чином, було опрацьовано основні способи перетворення ознак: створення похідних змінних, дискретизацію, масштабування та індикаторне кодування.